import Head from 'next/head';
import { BsGithub } from 'react-icons/Bs';
import { AiFillLinkedin, AiFillMail, AiFillHtml5 } from 'react-icons/Ai';
import { FaReact } from 'react-icons/Fa';
import { SiJavascript, SiTailwindcss, SiMysql } from 'react-icons/Si';
import { DiCss3Full } from 'react-icons/di';
import { FaPhp } from 'react-icons/fa';
import WorkList from '../components/WorkList';

export default function Home() {
	return (
		<div className=" w-full md:flex items-center justify-center">
			<Head>
				<title> Partha Changmai</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex flex-col gap-10 p-11 md:p-10 xl:w-4/6">
				<div>
					<p className="text-[#6133f5] text-md">Hey, My name is</p>
					<h1 className="text-4xl sm:text-7xl font-bold text-gray-300">
						Partha Pratim Changmai
					</h1>
					<h2 className="text-3xl sm:text-6xl font-bold text-[#8892b0]">
						I am a Front-end Developer.
					</h2>
					<p className="text-[#8892b0] md:text-lg py-4 max-2-[700px]">
						I’m a Front-end developer pursuing in building (and occasionally
						designing) exceptional digital experiences. Presently, I’m focused
						on building responsive front-end Web Applications.
					</p>
					<div>
						<p>Techstack that I know or have worked with.</p>

						<div className="text-4xl pt-3 pb-3 flex gap-2 md:gap-4">
							<FaReact />
							<SiJavascript />
							<AiFillHtml5 />
							<DiCss3Full />
							<SiTailwindcss />
							<BsGithub />
							<FaPhp />
							<SiMysql />
						</div>
					</div>
					<div className="outline-none pt-7">
						<div className="pl-1 ">Some of my projects: </div>
						<div className="grid md:grid-cols-4 gap-4 xl:gap-8 mt-4">
							<WorkList />
						</div>
					</div>
				</div>
				{/* 
				<div className="flex xl:hidden flex-row justify-center gap-11 md:px-6 ">
					<div className="bg-gray-900 p-1 md:p-2 rounded-lg shadow-md shadow-indigo-600 hover:shadow-indigo-300 hover:bg-[#333333]  ease-in-out duration-500">
						<BsGithub className="text-2xl md:text-3xl p-1 hover:p-0 cursor-pointer" />
					</div>
					<div className="bg-gray-900 p-1 md:p-2 rounded-lg shadow-md shadow-indigo-600 hover:shadow-indigo-300 hover:bg-[#0A66C2]  ease-in-out duration-500">
						<AiFillLinkedin className="text-2xl md:text-3xl p-1 hover:p-0 cursor-pointer" />
					</div>
					<div className="bg-gray-900 p-1 md:p-2 rounded-lg shadow-md shadow-indigo-600 hover:shadow-indigo-300 hover:bg-[#6fc2b0]  ease-in-out duration-500">
						<AiFillMail className="text-2xl md:text-3xl p-1 hover:p-0 cursor-pointer" />
					</div>
				</div> */}
			</div>
		</div>
	);
}
